spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/checkman
    user: checkman
    password: checkman
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/checkman
    username: checkman
    password: checkman
logging:
  level:
    liquibase : info
server:
  port: 9001