spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkman
    username: checkman
    password: checkman
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  rdbc2:
    url: r2dbc:postgresql://postgres@localhost:5432/checkman
logging:
  level:
    liquibase : info
server:
  port: 9001